### ISSUE TITLE
Add doi column to publications.csv

### ISSUE THREAD

**Issue by mhebing** [paneldata/soep-core#50]
@afuetterer I don't want to manipulate the 'real' metadata. For the upcoming review of my work, we would please need a doi column in the `publications.csv` with at least one example entry. Could you please add one example?

Pull request: https://github.com/ddionrails/ddionrails/pull/292

Issue: https://github.com/mhebing/ddionrails2/issues/492

**Comment by afuetterer** [comment]
What exactly do you want from me?

There is a column with DOIs in publications.csv. They follow the scheme "http://doi.org/{DOI}". Do you want a new column with only {DOI}?

**Comment by mhebing** [comment]
The most important thing for me was to have an example for Knut to review :-) Thanks for https://github.com/mhebing/ddionrails2/issues/492#issuecomment-468246497 !

Regarding the metadata: I didn't see the column first. Is it possible that the column header is missing for the DOI? And yes, as diskussed with Knut, the column content should be the doi without the URL prefix.
