### ISSUE TITLE
Integrate new concepts from Florian

### ISSUE THREAD

**Issue by mhebing** [paneldata/soep-core#6]
@jgoebel Wie wollen wir die Integrieren – kannst Du das gleich bei Dir einbauen?

@fgriese FYI

[new_concepts.xlsx](https://github.com/paneldata/soep-core/files/427447/new_concepts.xlsx)

> Die Liste mit neuen concepts für die P- und H-Variablen aus den Erhebungsjahren 2013 bis 2015 ist jetzt aufgefüllt.
> 
> Dabei sind wir mit lediglich 2 neu aufzunehmenden topics ausgekommen, die ich in dem Tabellenblatt "topics" eingeordnet habe:
> - labor market conditions (lmc)
> - anticipation minimum wage (amw)
> 
> Außerdem würden wir zwei topics auflösen. Hintergrund ist, dass in H2015 im Rahmen des Energie-Moduls Eigentümer und Mieter zusammen abgefragt wurden und die daraus entstandenen Variablen somit den beiden topics "for tenants" (fte) und "for owners" (fow) gleichermaßen gelten würden. Um den Block so unkompliziert wie möglich zu halten, würden wir daher das parent "housing costs" zur untersten Ebene werden lassen (find&replace: fte --> hoc; fow --> hoc).

**Comment by mhebing** [comment]
@jgoebel Hast Du Dir die hier eigentlich auch schon angeschaut?

**Comment by afuetterer** [comment]
Was this fixed?

**Comment by fgriese** [comment]
Noch nicht, ist aber richtig, dass das bei mir liegt. Im neuen Jahr werde ich dazu kommen, die Liste mit neuen concepts aufzufüllen.
