### ISSUE TITLE
Fix publications.csv

### ISSUE THREAD

**Issue by afuetterer** [paneldata/soep-core#66]
- [x] add "name" to the first 30 rows
- [ ] these "names" are not unique: 10704, 11013
- [x] remove column "period_name"
- [x] add column "study"
- [ ] fix invalid DOIs

**Comment by urahm** [comment]
will be fixed with the next update

**Comment by afuetterer** [comment]
@kwenzig @urahm : Would you please generate the next publications.csv like this?
https://raw.githubusercontent.com/paneldata/soep-core/ec8d96dfd84e2e1f285e0535450f2f007431c3e8/ddionrails/publications.csv

Use these headers:
`study,name,title,author,year,abstract,cite,type,studies,url,doi`

-> add study name, e.g. soep-core
-> remove period_name, as it is not used, that was my mistake

**Comment by afuetterer** [comment]
Also these values are not valid DOIs:

"289-306, DOI: 10.1007/BF01205404"
"doi:10.1016/j.econedurev.2007.10.005"
"0.1080/01419870802298439"
"DOI 10.1037/a0020385"
"10.1016/j.ssresearch.2012.03.013," <- trailing comma
"0.3238/arztebl.2012.0285"
"784-786"
"0.1016/j.econlet.2012.07.013"
"0.1080/09645292.2018.1463358"
"doi:10.1111/jomf.12518"

**Comment by urahm** [comment]
@kwenzig : Überarbeitung des Skriptes nötig:
- URLs werden bereinigt (nur noch eine URL im Feld), 
- doi werde ich als doi übergeben (nicht als url)
- evtl. study, study name, studies (müssen wir noch klären, was wie gemeint ist)

**Comment by afuetterer** [comment]
@urahm: Liebe Uta, hast du die Dateien schon erstellen können?
